"""Add is_published field to posts table

Revision ID: f56450e09b98
Revises: 001_create_posts_table
Create Date: 2025-11-11 11:17:05.343182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f56450e09b98'
down_revision: Union[str, None] = '001_create_posts_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('posts', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('posts', 'is_published')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
